name: Backend CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  DJANGO_SETTINGS_MODULE: pydo.settings
  DJANGO_SECRET_KEY: "django-insecure-=4#vn-xc@33tjoudn&ydv(yw+5y3p5@ss+qiue-m@i%=$6)^v="

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: pydouser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pydo
        ports:
        # will assign a random free host port
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup environment variables
      run: |
        cp .env.example .env
        export DJANGO_SETTINGS_MODULE=pydo.settings
    - name: Install dependencies
      working-directory: ./backend
      run: |
        sudo apt-get install libpq-dev 
        pip3 install coverage
        pip3 install pipenv
    - name: Linting
      working-directory: ./backend
      run: |
        pipenv install --dev
        source "$(pipenv --venv)"/bin/activate
        flake8 .
    - name: Migrations
      working-directory: ./backend
      run: |
        source "$(pipenv --venv)"/bin/activate
        python manage.py makemigrations
        python manage.py migrate
    - name: Coverage
      working-directory: ./backend
      run: |
        source "$(pipenv --venv)"/bin/activate
        pip3 install coverage
        coverage run --source='.' manage.py test
  